### PR TITLE
Add CodeQL checks (main)

### PR DESCRIPTION
**Pull request by marcrohlfs**
autoclose none

### CODE REVIEW

**Review by uwilken — APPROVED** [review]
Looking good but I don't know exactly where to find the results of a run besides the action runs itself below https://github.com/CoreMedia/coremedia-headless-commerce/actions

Since we really won't ever look into this on a regular basis, one could think about a teams channel to push messages, if the workspace becomes critical security-wise.

**Comment by uwilken** [comment]
Found smth like uploading results to /home/runner/work/coremedia-headless-commerce/results/java.sarif....but how to see them?

**Comment by marcrohlfs** [comment]
You (almost) don't see them, because the action finished successfully. Below, You should see _2 successful checks_. Expanding them leads You to the details. They'll be expanded automatically when a check has failed. It should be equal to the behavior that is configured for the campaign management repos.

The one that is marked as _Required_ is the more interesting one (don't know why it shows two checks anyway). It prevents pull requests from being merged when checks fail (for now, this this can be bypassed, see failed PR #16). And looking at the details of the check, You'll find some warnings, but they're of low severity and thus don't cause the check to be considered as failed.

**Comment by uwilken** [comment]
👍

**Pull request merged**
